# Generated by Django 3.0.6 on 2020-05-11 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0002_auto_20200511_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_tutor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
