# Generated by Django 3.0.6 on 2020-05-11 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0003_appointment_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_student', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MAT', 'Mathematics'), ('ENG', 'English'), ('PHY', 'Physics')], max_length=3)),
                ('price', models.PositiveIntegerField()),
                ('ad_type', models.CharField(choices=[('T', 'TEACH'), ('L', 'LEARN')], max_length=1)),
                ('is_availible', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='ad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_ad', to='general.Ad'),
            preserve_default=False,
        ),
    ]
